// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using setPlay_C_.Data;

#nullable disable

namespace setPlay_C_.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204145932_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("setPlay_C_.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentDatetime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AcceptedSongId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("longtext");

                    b.Property<string>("BpmRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CashReward")
                        .HasColumnType("int");

                    b.Property<Guid>("DJId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EventMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PostedMoment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("PostedMoment"));

                    b.Property<string>("SongLengthRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedSongId");

                    b.HasIndex("DJId");

                    b.HasIndex("VenueId");

                    b.ToTable("Gigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            AcceptedSongId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            BackgroundImage = "https://picsum.photos/seed/gig1/1200/600",
                            BpmRange = "[120,128]",
                            CashReward = 35,
                            DJId = new Guid("3ed3c11d-f4ad-4749-b30b-6466e9e40277"),
                            EventMoment = new DateTime(2026, 2, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Aurora Nights",
                            Genre = 13,
                            IsCancelled = false,
                            PostedMoment = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            SongLengthRange = "[180,240]",
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            AcceptedSongId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            BackgroundImage = "https://picsum.photos/seed/gig2/1200/600",
                            BpmRange = "[128,135]",
                            CashReward = 50,
                            DJId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EventMoment = new DateTime(2026, 3, 1, 23, 30, 0, 0, DateTimeKind.Utc),
                            EventName = "Circuit Breaker",
                            Genre = 28,
                            IsCancelled = false,
                            PostedMoment = new DateTime(2026, 2, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            SongLengthRange = "[240,330]",
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            AcceptedSongId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            BackgroundImage = "https://picsum.photos/seed/gig3/1200/600",
                            BpmRange = "[136,142]",
                            CashReward = 75,
                            DJId = new Guid("3ed3c11d-f4ad-4749-b30b-6466e9e40277"),
                            EventMoment = new DateTime(2026, 4, 6, 5, 30, 0, 0, DateTimeKind.Utc),
                            EventName = "Rooftop Sunrise",
                            Genre = 29,
                            IsCancelled = false,
                            PostedMoment = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            SongLengthRange = "[240,360]",
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3")
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.GigSavedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GigId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("UserId");

                    b.ToTable("GigSavedByUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1"),
                            GigId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2"),
                            GigId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GigId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("Offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            GigId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            IsHidden = false,
                            SongId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            GigId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            IsHidden = false,
                            SongId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Socials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Socials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff1"),
                            Key = "djnova",
                            Platform = "Instagram",
                            Url = "https://instagram.com/djnova",
                            UserId = new Guid("3ed3c11d-f4ad-4749-b30b-6466e9e40277")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-fffffffffff4"),
                            Key = "producer-luna",
                            Platform = "YouTube",
                            Url = "https://youtube.com/@producer-luna",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BpmRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedMoment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedMoment"));

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("SongLength")
                        .HasColumnType("time(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BpmRange = "[120,128]",
                            CreatedMoment = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Genre = 13,
                            IsArchived = false,
                            SongLength = new TimeSpan(0, 0, 3, 24, 0),
                            Title = "Neon Drive",
                            Uri = "https://example.com/audio/neon-drive"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            AuthorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BpmRange = "[128,135]",
                            CreatedMoment = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Genre = 28,
                            IsArchived = false,
                            SongLength = new TimeSpan(0, 0, 4, 10, 0),
                            Title = "Midnight Circuit",
                            Uri = "https://example.com/audio/midnight-circuit"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BpmRange = "[136,142]",
                            CreatedMoment = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Genre = 29,
                            IsArchived = false,
                            SongLength = new TimeSpan(0, 0, 5, 5, 0),
                            Title = "Sunrise Bloom",
                            Uri = "https://example.com/audio/sunrise-bloom"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            AuthorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BpmRange = "[170,176]",
                            CreatedMoment = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Genre = 7,
                            IsArchived = false,
                            SongLength = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "Low Tide",
                            Uri = "https://example.com/audio/low-tide"
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreferedUserType")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ed3c11d-f4ad-4749-b30b-6466e9e40277"),
                            Avatar = "https://i.pravatar.cc/300?img=12",
                            PreferedUserType = 0,
                            Rating = 4.7000000000000002,
                            Username = "Pharaoh"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Avatar = "https://i.pravatar.cc/300?img=32",
                            PreferedUserType = 0,
                            Rating = 4.2999999999999998,
                            Username = "Pulse"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Avatar = "https://i.pravatar.cc/300?img=5",
                            PreferedUserType = 1,
                            Rating = 0.0,
                            Username = "Echo"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Avatar = "https://i.pravatar.cc/300?img=8",
                            PreferedUserType = 1,
                            Rating = 4.2000000000000002,
                            Username = "Luna"
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Location = "Berlin, DE",
                            Name = "Club Aurora"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Location = "Amsterdam, NL",
                            Name = "Warehouse19"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            Location = "Lisbon, PT",
                            Name = "Skyline Rooftop"
                        });
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.User", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Song", "AcceptedSong")
                        .WithMany("Gigs")
                        .HasForeignKey("AcceptedSongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.User", "DJ")
                        .WithMany("DJGigs")
                        .HasForeignKey("DJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.Venue", "Venue")
                        .WithMany("Gigs")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedSong");

                    b.Navigation("DJ");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.GigSavedUser", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Gig", "Gig")
                        .WithMany("GigSavedByUser")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.User", "User")
                        .WithMany("ProducerGigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Offer", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Gig", "Gig")
                        .WithMany("Offers")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.Song", "Song")
                        .WithOne("Offer")
                        .HasForeignKey("setPlay_C_.Data.Entities.Offer", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Socials", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.User", "User")
                        .WithMany("Socials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.User", "Author")
                        .WithMany("Songs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.Navigation("GigSavedByUser");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.User", b =>
                {
                    b.Navigation("DJGigs");

                    b.Navigation("ProducerGigs");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("Socials");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Venue", b =>
                {
                    b.Navigation("Gigs");
                });
#pragma warning restore 612, 618
        }
    }
}
