// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using setPlay_C_.Data;

#nullable disable

namespace setPlay_C_.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203180951_AddRaitingToUser")]
    partial class AddRaitingToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AcceptedSongId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("longtext");

                    b.Property<string>("BpmRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CashReward")
                        .HasColumnType("int");

                    b.Property<Guid>("DJId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EventMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PostedMoment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("PostedMoment"));

                    b.Property<string>("SongLengthRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedSongId");

                    b.HasIndex("DJId");

                    b.HasIndex("VenueId");

                    b.ToTable("Gigs", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.GigProducer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GigId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("ProducerId");

                    b.ToTable("GigProducers");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GigId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Socials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Socials", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BpmRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedMoment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedMoment"));

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("SongLength")
                        .HasColumnType("time(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreferedUserType")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Song", "AcceptedSong")
                        .WithMany("Gigs")
                        .HasForeignKey("AcceptedSongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.User", "DJ")
                        .WithMany("DJGigs")
                        .HasForeignKey("DJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.Venue", "Venue")
                        .WithMany("Gigs")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedSong");

                    b.Navigation("DJ");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.GigProducer", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Gig", "Gig")
                        .WithMany("GigSavedByProducers")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.User", "Producer")
                        .WithMany("ProducerGigs")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Offer", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.Gig", "Gig")
                        .WithMany("Offers")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("setPlay_C_.Data.Entities.Song", "Song")
                        .WithOne("Offer")
                        .HasForeignKey("setPlay_C_.Data.Entities.Offer", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Socials", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.User", "User")
                        .WithMany("Socials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.HasOne("setPlay_C_.Data.Entities.User", "Author")
                        .WithMany("Songs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Gig", b =>
                {
                    b.Navigation("GigSavedByProducers");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Song", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.User", b =>
                {
                    b.Navigation("DJGigs");

                    b.Navigation("ProducerGigs");

                    b.Navigation("Socials");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("setPlay_C_.Data.Entities.Venue", b =>
                {
                    b.Navigation("Gigs");
                });
#pragma warning restore 612, 618
        }
    }
}
